openapi: 3.0.3
info:
  title: Agent Service API
  version: 1.0.0
  description: API for agent profile management

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /agents:
    get:
      summary: Get agent profile by user ID
      description: Retrieve agent profile information for a specific user
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: User ID to retrieve agent profile for
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Agent profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      agent:
                        $ref: '#/components/schemas/Agent'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Agent profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Agent:
      type: object
      required:
        - id
        - userId
      properties:
        id:
          type: string
          format: uuid
          description: Agent unique identifier
        userId:
          type: string
          format: uuid
          description: Associated user ID
        licenseNumber:
          type: string
          maxLength: 50
          description: Agent license number
        specialization:
          type: string
          maxLength: 200
          description: Agent specialization
        yearsOfExperience:
          type: integer
          minimum: 0
          description: Years of experience
        bio:
          type: string
          maxLength: 2000
          description: Agent biography
        contactNumber:
          type: string
          description: Contact phone number
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "VALIDATION_ERROR"
            message:
              type: string
              example: "Invalid input parameters"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT